-- BAN-302 Pass 3a — AIA Billing v1.1 entity schema (15 tables)
-- Source: AIA Billing + SOV Trunk Spec v1.1 §14.1
-- Ratification: BAN-302 D4 (AIA events map to canonical 34) — Sean 2026-05-17 HST
--
-- Tables created in FK-dependency order (parents before children):
--   1. sov_versions
--   2. schedule_of_values         (FK sov_versions)
--   3. billing_format_config
--   4. deposit_terms
--   5. tm_authorizations          (FK schedule_of_values)
--   6. pay_applications           (FK sov_versions)
--   7. pay_app_line_items         (FK pay_applications, schedule_of_values, tm_authorizations)
--   8. pay_app_states             (FK pay_applications)
--   9. notarization_sessions      (FK pay_applications)
--  10. lien_waivers               (FK pay_applications, notarization_sessions)
--  11. cash_receipts              (FK pay_applications)
--  12. retainage_holdings         (FK pay_applications, pay_app_line_items)
--  13. handoff_validations        (FK sov_versions)
--  14. tm_tickets                 (FK tm_authorizations, pay_applications)
--  15. textura_submissions        (FK pay_applications)
--
-- All entities inherit test-vs-production status from engagements.is_test_project per
-- TPA spec §4.2 + AIA v1.1 §14.2 — no per-entity test_data flag (cf. field_events,
-- which carries explicit test_data because Activity Spine queries cross projects).
--
-- Activity Spine event_contract.ts NOT modified. All AIA-emitted events map to the
-- canonical 34 per BAN-302 D4 + ADR-NNN (this PR) — see ADR for full mapping table.
--
-- DOWN SQL (manual, if Sean directs): DROP TABLE IF EXISTS each, in reverse FK order.

CREATE TABLE IF NOT EXISTS public.sov_versions (
  sov_version_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants (tenant_id),
  engagement_id uuid NOT NULL REFERENCES public.engagements (engagement_id),
  version_number integer NOT NULL,
  state text NOT NULL DEFAULT 'NONE',
  locked_at timestamptz,
  retired_at timestamptz,
  source_kind text NOT NULL DEFAULT 'ESTIMATOR_INITIAL',
  source_ref_id uuid,
  source_ref_type text,
  manager_override_by uuid REFERENCES public.users (user_id),
  manager_override_reason text,
  total_value numeric(14,2),
  created_by uuid REFERENCES public.users (user_id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE public.sov_versions
  DROP CONSTRAINT IF EXISTS sov_versions_engagement_version_uidx;
ALTER TABLE public.sov_versions
  ADD CONSTRAINT sov_versions_engagement_version_uidx UNIQUE (tenant_id, engagement_id, version_number);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS sov_versions_engagement_state_idx
  ON public.sov_versions (tenant_id, engagement_id, state);
--> statement-breakpoint
ALTER TABLE public.sov_versions
  DROP CONSTRAINT IF EXISTS sov_versions_state_check;
ALTER TABLE public.sov_versions
  ADD CONSTRAINT sov_versions_state_check
  CHECK (state IN ('NONE','DRAFT_AUTOGENERATED','DRAFT_ESTIMATOR_STRUCTURED','APPROVED_INTERNAL','IN_GC_NEGOTIATION','LOCKED','IN_RECONCILIATION','RETIRED')) NOT VALID;
ALTER TABLE public.sov_versions VALIDATE CONSTRAINT sov_versions_state_check;
--> statement-breakpoint
ALTER TABLE public.sov_versions
  DROP CONSTRAINT IF EXISTS sov_versions_source_kind_check;
ALTER TABLE public.sov_versions
  ADD CONSTRAINT sov_versions_source_kind_check
  CHECK (source_kind IN ('ESTIMATOR_INITIAL','CO_DRIVEN','TM_AUTH_DRIVEN','MANAGER_OVERRIDE','RECONCILIATION')) NOT VALID;
ALTER TABLE public.sov_versions VALIDATE CONSTRAINT sov_versions_source_kind_check;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS public.schedule_of_values (
  sov_line_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants (tenant_id),
  engagement_id uuid NOT NULL REFERENCES public.engagements (engagement_id),
  sov_version_id uuid NOT NULL REFERENCES public.sov_versions (sov_version_id) ON DELETE CASCADE,
  line_number integer NOT NULL,
  description text NOT NULL,
  cost_code text,
  scheduled_value numeric(14,2) NOT NULL DEFAULT 0,
  line_type text NOT NULL DEFAULT 'LUMP_SUM',
  tm_authorization_id uuid,
  retainage_pct numeric(5,2),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE public.schedule_of_values
  DROP CONSTRAINT IF EXISTS schedule_of_values_version_line_uidx;
ALTER TABLE public.schedule_of_values
  ADD CONSTRAINT schedule_of_values_version_line_uidx UNIQUE (tenant_id, sov_version_id, line_number);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS schedule_of_values_engagement_idx
  ON public.schedule_of_values (tenant_id, engagement_id);
CREATE INDEX IF NOT EXISTS schedule_of_values_tm_auth_idx
  ON public.schedule_of_values (tenant_id, tm_authorization_id);
--> statement-breakpoint
ALTER TABLE public.schedule_of_values
  DROP CONSTRAINT IF EXISTS schedule_of_values_line_type_check;
ALTER TABLE public.schedule_of_values
  ADD CONSTRAINT schedule_of_values_line_type_check
  CHECK (line_type IN ('LUMP_SUM','TM_AUTHORIZATION','MOBILIZATION','RETAINAGE_RELEASE','DEPOSIT_DRAW_DOWN','STORED_MATERIALS','OTHER')) NOT VALID;
ALTER TABLE public.schedule_of_values VALIDATE CONSTRAINT schedule_of_values_line_type_check;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS public.billing_format_config (
  billing_config_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants (tenant_id),
  engagement_id uuid NOT NULL REFERENCES public.engagements (engagement_id),
  billing_format text NOT NULL,
  gc_billing_intake_platform text NOT NULL DEFAULT 'DIRECT',
  custom_template_ref text,
  retainage_pct numeric(5,2) NOT NULL DEFAULT 10,
  retainage_release_trigger text NOT NULL DEFAULT 'SUBSTANTIAL_COMPLETION',
  payment_terms text NOT NULL DEFAULT 'NET_30',
  notarization_required boolean NOT NULL DEFAULT false,
  architect_cert_required boolean NOT NULL DEFAULT false,
  lien_waiver_required boolean NOT NULL DEFAULT false,
  get_handling text NOT NULL DEFAULT 'SUMMARY_LINE_ONLY',
  stored_materials_policy text NOT NULL DEFAULT 'G703_COLUMN_G',
  gc_certifier_name text,
  gc_certifier_email text,
  gc_certifier_title text,
  architect_certifier_name text,
  architect_certifier_email text,
  architect_certifier_title text,
  billing_period_definition text NOT NULL DEFAULT 'MONTHLY_CALENDAR',
  tm_authorizations_permitted boolean NOT NULL DEFAULT true,
  tm_billing_doc text NOT NULL DEFAULT 'SAME_AS_PAY_APP',
  pay_app_sequence_numbering text NOT NULL DEFAULT 'CONTINUOUS',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE public.billing_format_config
  DROP CONSTRAINT IF EXISTS billing_format_config_engagement_uidx;
ALTER TABLE public.billing_format_config
  ADD CONSTRAINT billing_format_config_engagement_uidx UNIQUE (tenant_id, engagement_id);
--> statement-breakpoint
ALTER TABLE public.billing_format_config
  DROP CONSTRAINT IF EXISTS billing_format_config_billing_format_check;
ALTER TABLE public.billing_format_config
  ADD CONSTRAINT billing_format_config_billing_format_check
  CHECK (billing_format IN ('AIA_G702_G703','TEXTURA_CSV_EXPORT','CUSTOM_TEMPLATE','TM_INVOICE','LUMP_SUM_PROGRESS','MIXED')) NOT VALID;
ALTER TABLE public.billing_format_config VALIDATE CONSTRAINT billing_format_config_billing_format_check;
--> statement-breakpoint
ALTER TABLE public.billing_format_config
  DROP CONSTRAINT IF EXISTS billing_format_config_intake_platform_check;
ALTER TABLE public.billing_format_config
  ADD CONSTRAINT billing_format_config_intake_platform_check
  CHECK (gc_billing_intake_platform IN ('TEXTURA','DIRECT','OTHER')) NOT VALID;
ALTER TABLE public.billing_format_config VALIDATE CONSTRAINT billing_format_config_intake_platform_check;
--> statement-breakpoint
ALTER TABLE public.billing_format_config
  DROP CONSTRAINT IF EXISTS billing_format_config_retainage_trigger_check;
ALTER TABLE public.billing_format_config
  ADD CONSTRAINT billing_format_config_retainage_trigger_check
  CHECK (retainage_release_trigger IN ('SUBSTANTIAL_COMPLETION','FINAL_PAYMENT','CONTRACT_DATE','MANUAL')) NOT VALID;
ALTER TABLE public.billing_format_config VALIDATE CONSTRAINT billing_format_config_retainage_trigger_check;
--> statement-breakpoint
ALTER TABLE public.billing_format_config
  DROP CONSTRAINT IF EXISTS billing_format_config_payment_terms_check;
ALTER TABLE public.billing_format_config
  ADD CONSTRAINT billing_format_config_payment_terms_check
  CHECK (payment_terms IN ('NET_30','NET_45','NET_60','PAY_WHEN_PAID','CONTRACT_DEFINED')) NOT VALID;
ALTER TABLE public.billing_format_config VALIDATE CONSTRAINT billing_format_config_payment_terms_check;
--> statement-breakpoint
ALTER TABLE public.billing_format_config
  DROP CONSTRAINT IF EXISTS billing_format_config_get_handling_check;
ALTER TABLE public.billing_format_config
  ADD CONSTRAINT billing_format_config_get_handling_check
  CHECK (get_handling IN ('SUMMARY_LINE_ONLY','NOT_APPLICABLE')) NOT VALID;
ALTER TABLE public.billing_format_config VALIDATE CONSTRAINT billing_format_config_get_handling_check;
--> statement-breakpoint
ALTER TABLE public.billing_format_config
  DROP CONSTRAINT IF EXISTS billing_format_config_stored_materials_policy_check;
ALTER TABLE public.billing_format_config
  ADD CONSTRAINT billing_format_config_stored_materials_policy_check
  CHECK (stored_materials_policy IN ('G703_COLUMN_G','SEPARATE_LINE','NOT_PERMITTED')) NOT VALID;
ALTER TABLE public.billing_format_config VALIDATE CONSTRAINT billing_format_config_stored_materials_policy_check;
--> statement-breakpoint
ALTER TABLE public.billing_format_config
  DROP CONSTRAINT IF EXISTS billing_format_config_billing_period_check;
ALTER TABLE public.billing_format_config
  ADD CONSTRAINT billing_format_config_billing_period_check
  CHECK (billing_period_definition IN ('MONTHLY_CALENDAR','MONTHLY_FROM_NTP','BIWEEKLY','CONTRACT_DEFINED')) NOT VALID;
ALTER TABLE public.billing_format_config VALIDATE CONSTRAINT billing_format_config_billing_period_check;
--> statement-breakpoint
ALTER TABLE public.billing_format_config
  DROP CONSTRAINT IF EXISTS billing_format_config_tm_billing_doc_check;
ALTER TABLE public.billing_format_config
  ADD CONSTRAINT billing_format_config_tm_billing_doc_check
  CHECK (tm_billing_doc IN ('SAME_AS_PAY_APP','SEPARATE_TM_INVOICE')) NOT VALID;
ALTER TABLE public.billing_format_config VALIDATE CONSTRAINT billing_format_config_tm_billing_doc_check;
--> statement-breakpoint
ALTER TABLE public.billing_format_config
  DROP CONSTRAINT IF EXISTS billing_format_config_pay_app_seq_check;
ALTER TABLE public.billing_format_config
  ADD CONSTRAINT billing_format_config_pay_app_seq_check
  CHECK (pay_app_sequence_numbering IN ('CONTINUOUS','RESTART_PER_PHASE')) NOT VALID;
ALTER TABLE public.billing_format_config VALIDATE CONSTRAINT billing_format_config_pay_app_seq_check;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS public.deposit_terms (
  deposit_terms_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants (tenant_id),
  engagement_id uuid NOT NULL REFERENCES public.engagements (engagement_id),
  deposit_pattern text NOT NULL DEFAULT 'NONE',
  deposit_amount numeric(14,2),
  deposit_amount_pct numeric(5,2),
  deposit_due_date date,
  deposit_received_date date,
  draw_down_logic text NOT NULL DEFAULT 'AUTO',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE public.deposit_terms
  DROP CONSTRAINT IF EXISTS deposit_terms_engagement_uidx;
ALTER TABLE public.deposit_terms
  ADD CONSTRAINT deposit_terms_engagement_uidx UNIQUE (tenant_id, engagement_id);
--> statement-breakpoint
ALTER TABLE public.deposit_terms
  DROP CONSTRAINT IF EXISTS deposit_terms_pattern_check;
ALTER TABLE public.deposit_terms
  ADD CONSTRAINT deposit_terms_pattern_check
  CHECK (deposit_pattern IN ('MOBILIZATION_LINE','SEPARATE_INVOICE','STORED_MATERIALS','NONE')) NOT VALID;
ALTER TABLE public.deposit_terms VALIDATE CONSTRAINT deposit_terms_pattern_check;
--> statement-breakpoint
ALTER TABLE public.deposit_terms
  DROP CONSTRAINT IF EXISTS deposit_terms_draw_down_check;
ALTER TABLE public.deposit_terms
  ADD CONSTRAINT deposit_terms_draw_down_check
  CHECK (draw_down_logic IN ('AUTO','MANUAL')) NOT VALID;
ALTER TABLE public.deposit_terms VALIDATE CONSTRAINT deposit_terms_draw_down_check;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS public.tm_authorizations (
  tm_auth_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants (tenant_id),
  engagement_id uuid NOT NULL REFERENCES public.engagements (engagement_id),
  authorization_number text NOT NULL,
  title text NOT NULL,
  description text,
  authorized_by_name text,
  authorized_by_title text,
  authorized_by_date date,
  authorization_method text NOT NULL DEFAULT 'OTHER',
  authorization_evidence_ref text,
  scope_basis text NOT NULL DEFAULT 'DURING_CONSTRUCTION',
  rate_structure text NOT NULL DEFAULT 'STANDARD_TM',
  rate_per_hour_labor numeric(10,2),
  rate_per_hour_supervision numeric(10,2),
  materials_markup_pct numeric(5,2),
  not_to_exceed_amount numeric(14,2),
  sov_line_id uuid REFERENCES public.schedule_of_values (sov_line_id),
  status text NOT NULL DEFAULT 'ACTIVE',
  converted_to_co_ref text,
  closed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE public.tm_authorizations
  DROP CONSTRAINT IF EXISTS tm_authorizations_engagement_number_uidx;
ALTER TABLE public.tm_authorizations
  ADD CONSTRAINT tm_authorizations_engagement_number_uidx UNIQUE (tenant_id, engagement_id, authorization_number);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS tm_authorizations_engagement_status_idx
  ON public.tm_authorizations (tenant_id, engagement_id, status);
--> statement-breakpoint
ALTER TABLE public.tm_authorizations
  DROP CONSTRAINT IF EXISTS tm_authorizations_method_check;
ALTER TABLE public.tm_authorizations
  ADD CONSTRAINT tm_authorizations_method_check
  CHECK (authorization_method IN ('VERBAL','EMAIL','WRITTEN_WORK_ORDER','OTHER')) NOT VALID;
ALTER TABLE public.tm_authorizations VALIDATE CONSTRAINT tm_authorizations_method_check;
--> statement-breakpoint
ALTER TABLE public.tm_authorizations
  DROP CONSTRAINT IF EXISTS tm_authorizations_scope_basis_check;
ALTER TABLE public.tm_authorizations
  ADD CONSTRAINT tm_authorizations_scope_basis_check
  CHECK (scope_basis IN ('PUNCHLIST_PERIOD','DURING_CONSTRUCTION','OTHER')) NOT VALID;
ALTER TABLE public.tm_authorizations VALIDATE CONSTRAINT tm_authorizations_scope_basis_check;
--> statement-breakpoint
ALTER TABLE public.tm_authorizations
  DROP CONSTRAINT IF EXISTS tm_authorizations_rate_structure_check;
ALTER TABLE public.tm_authorizations
  ADD CONSTRAINT tm_authorizations_rate_structure_check
  CHECK (rate_structure IN ('STANDARD_TM','NEGOTIATED_RATE','NTE')) NOT VALID;
ALTER TABLE public.tm_authorizations VALIDATE CONSTRAINT tm_authorizations_rate_structure_check;
--> statement-breakpoint
ALTER TABLE public.tm_authorizations
  DROP CONSTRAINT IF EXISTS tm_authorizations_status_check;
ALTER TABLE public.tm_authorizations
  ADD CONSTRAINT tm_authorizations_status_check
  CHECK (status IN ('ACTIVE','CLOSED','DISPUTED','CONVERTED_TO_CO')) NOT VALID;
ALTER TABLE public.tm_authorizations VALIDATE CONSTRAINT tm_authorizations_status_check;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS public.pay_applications (
  pay_app_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants (tenant_id),
  engagement_id uuid NOT NULL REFERENCES public.engagements (engagement_id),
  pay_app_number integer NOT NULL,
  period_start date NOT NULL,
  period_end date NOT NULL,
  state text NOT NULL DEFAULT 'PENDING_DRAFT',
  sov_version_id uuid REFERENCES public.sov_versions (sov_version_id),
  contract_sum_original numeric(14,2),
  net_change_by_co numeric(14,2) NOT NULL DEFAULT 0,
  contract_sum_to_date numeric(14,2),
  work_completed_to_date numeric(14,2) NOT NULL DEFAULT 0,
  stored_materials_to_date numeric(14,2) NOT NULL DEFAULT 0,
  retainage_held numeric(14,2) NOT NULL DEFAULT 0,
  total_earned_less_retainage numeric(14,2) NOT NULL DEFAULT 0,
  less_previous_certificates numeric(14,2) NOT NULL DEFAULT 0,
  current_amount_due numeric(14,2) NOT NULL DEFAULT 0,
  notarization_required boolean NOT NULL DEFAULT false,
  architect_cert_required boolean NOT NULL DEFAULT false,
  submitted_at timestamptz,
  architect_certified_at timestamptz,
  gc_approved_at timestamptz,
  rejected_at timestamptz,
  rejection_reason text,
  is_retainage_release boolean NOT NULL DEFAULT false,
  created_by uuid REFERENCES public.users (user_id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE public.pay_applications
  DROP CONSTRAINT IF EXISTS pay_applications_engagement_number_uidx;
ALTER TABLE public.pay_applications
  ADD CONSTRAINT pay_applications_engagement_number_uidx UNIQUE (tenant_id, engagement_id, pay_app_number);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS pay_applications_engagement_state_idx
  ON public.pay_applications (tenant_id, engagement_id, state);
CREATE INDEX IF NOT EXISTS pay_applications_period_idx
  ON public.pay_applications (tenant_id, engagement_id, period_end);
--> statement-breakpoint
ALTER TABLE public.pay_applications
  DROP CONSTRAINT IF EXISTS pay_applications_state_check;
ALTER TABLE public.pay_applications
  ADD CONSTRAINT pay_applications_state_check
  CHECK (state IN ('PENDING_DRAFT','READY_FOR_NOTARIZATION','READY_FOR_SUBMISSION','SUBMITTED','ARCHITECT_CERTIFIED','GC_APPROVED','PAID_PARTIAL','PAID_FULL','REJECTED')) NOT VALID;
ALTER TABLE public.pay_applications VALIDATE CONSTRAINT pay_applications_state_check;
--> statement-breakpoint
ALTER TABLE public.pay_applications
  DROP CONSTRAINT IF EXISTS pay_applications_period_order_check;
ALTER TABLE public.pay_applications
  ADD CONSTRAINT pay_applications_period_order_check
  CHECK (period_end >= period_start) NOT VALID;
ALTER TABLE public.pay_applications VALIDATE CONSTRAINT pay_applications_period_order_check;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS public.pay_app_line_items (
  pay_app_line_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants (tenant_id),
  pay_app_id uuid NOT NULL REFERENCES public.pay_applications (pay_app_id) ON DELETE CASCADE,
  sov_line_id uuid REFERENCES public.schedule_of_values (sov_line_id),
  tm_authorization_id uuid REFERENCES public.tm_authorizations (tm_auth_id),
  line_number integer NOT NULL,
  line_type text NOT NULL DEFAULT 'LUMP_SUM',
  description text NOT NULL,
  scheduled_value numeric(14,2) NOT NULL DEFAULT 0,
  work_completed_previous numeric(14,2) NOT NULL DEFAULT 0,
  work_completed_this_period numeric(14,2) NOT NULL DEFAULT 0,
  stored_materials numeric(14,2) NOT NULL DEFAULT 0,
  total_completed_and_stored numeric(14,2) NOT NULL DEFAULT 0,
  percent_complete numeric(5,2) NOT NULL DEFAULT 0,
  retainage_held numeric(14,2) NOT NULL DEFAULT 0,
  balance_to_finish numeric(14,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE public.pay_app_line_items
  DROP CONSTRAINT IF EXISTS pay_app_line_items_pay_app_line_uidx;
ALTER TABLE public.pay_app_line_items
  ADD CONSTRAINT pay_app_line_items_pay_app_line_uidx UNIQUE (pay_app_id, line_number);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS pay_app_line_items_sov_line_idx
  ON public.pay_app_line_items (tenant_id, sov_line_id);
--> statement-breakpoint
ALTER TABLE public.pay_app_line_items
  DROP CONSTRAINT IF EXISTS pay_app_line_items_line_type_check;
ALTER TABLE public.pay_app_line_items
  ADD CONSTRAINT pay_app_line_items_line_type_check
  CHECK (line_type IN ('LUMP_SUM','TM_AUTHORIZATION','MOBILIZATION','RETAINAGE_RELEASE','DEPOSIT_DRAW_DOWN','STORED_MATERIALS','OTHER')) NOT VALID;
ALTER TABLE public.pay_app_line_items VALIDATE CONSTRAINT pay_app_line_items_line_type_check;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS public.pay_app_states (
  state_change_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants (tenant_id),
  pay_app_id uuid NOT NULL REFERENCES public.pay_applications (pay_app_id) ON DELETE CASCADE,
  from_state text,
  to_state text NOT NULL,
  changed_by uuid REFERENCES public.users (user_id),
  changed_at timestamptz NOT NULL DEFAULT now(),
  reason text,
  created_at timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS pay_app_states_pay_app_idx
  ON public.pay_app_states (pay_app_id, changed_at);
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS public.notarization_sessions (
  session_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants (tenant_id),
  engagement_id uuid NOT NULL REFERENCES public.engagements (engagement_id),
  target_kind text NOT NULL,
  pay_app_id uuid REFERENCES public.pay_applications (pay_app_id),
  provider text NOT NULL DEFAULT 'PROOF',
  provider_session_id text,
  provider_session_url text,
  signer_user_id uuid REFERENCES public.users (user_id),
  notary_name text,
  notary_cert_ref text,
  state text NOT NULL DEFAULT 'CREATED',
  cost_amount numeric(10,2),
  completed_at timestamptz,
  failure_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS notarization_sessions_engagement_idx
  ON public.notarization_sessions (tenant_id, engagement_id, state);
CREATE INDEX IF NOT EXISTS notarization_sessions_pay_app_idx
  ON public.notarization_sessions (tenant_id, pay_app_id);
--> statement-breakpoint
ALTER TABLE public.notarization_sessions
  DROP CONSTRAINT IF EXISTS notarization_sessions_target_kind_check;
ALTER TABLE public.notarization_sessions
  ADD CONSTRAINT notarization_sessions_target_kind_check
  CHECK (target_kind IN ('PAY_APP','LIEN_WAIVER')) NOT VALID;
ALTER TABLE public.notarization_sessions VALIDATE CONSTRAINT notarization_sessions_target_kind_check;
--> statement-breakpoint
ALTER TABLE public.notarization_sessions
  DROP CONSTRAINT IF EXISTS notarization_sessions_state_check;
ALTER TABLE public.notarization_sessions
  ADD CONSTRAINT notarization_sessions_state_check
  CHECK (state IN ('CREATED','IN_PROGRESS','COMPLETED','FAILED','CANCELLED')) NOT VALID;
ALTER TABLE public.notarization_sessions VALIDATE CONSTRAINT notarization_sessions_state_check;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS public.lien_waivers (
  waiver_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants (tenant_id),
  engagement_id uuid NOT NULL REFERENCES public.engagements (engagement_id),
  pay_app_id uuid REFERENCES public.pay_applications (pay_app_id),
  waiver_type text NOT NULL,
  waiver_amount numeric(14,2),
  through_date date,
  state text NOT NULL DEFAULT 'PENDING',
  notarization_session_id uuid REFERENCES public.notarization_sessions (session_id),
  drive_file_ref text,
  delivered_at timestamptz,
  delivered_method text,
  released_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS lien_waivers_engagement_state_idx
  ON public.lien_waivers (tenant_id, engagement_id, state);
CREATE INDEX IF NOT EXISTS lien_waivers_pay_app_idx
  ON public.lien_waivers (tenant_id, pay_app_id);
--> statement-breakpoint
ALTER TABLE public.lien_waivers
  DROP CONSTRAINT IF EXISTS lien_waivers_type_check;
ALTER TABLE public.lien_waivers
  ADD CONSTRAINT lien_waivers_type_check
  CHECK (waiver_type IN ('CONDITIONAL_PROGRESS','UNCONDITIONAL_PROGRESS','CONDITIONAL_FINAL','UNCONDITIONAL_FINAL')) NOT VALID;
ALTER TABLE public.lien_waivers VALIDATE CONSTRAINT lien_waivers_type_check;
--> statement-breakpoint
ALTER TABLE public.lien_waivers
  DROP CONSTRAINT IF EXISTS lien_waivers_state_check;
ALTER TABLE public.lien_waivers
  ADD CONSTRAINT lien_waivers_state_check
  CHECK (state IN ('PENDING','NOTARIZED','FILED','DELIVERED','RELEASED','VOIDED')) NOT VALID;
ALTER TABLE public.lien_waivers VALIDATE CONSTRAINT lien_waivers_state_check;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS public.cash_receipts (
  receipt_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants (tenant_id),
  engagement_id uuid NOT NULL REFERENCES public.engagements (engagement_id),
  pay_app_id uuid REFERENCES public.pay_applications (pay_app_id),
  receipt_date date NOT NULL,
  amount numeric(14,2) NOT NULL,
  source text NOT NULL DEFAULT 'MANUAL',
  qbo_payment_ref text,
  reconciliation_status text NOT NULL DEFAULT 'UNMATCHED',
  matched_by uuid REFERENCES public.users (user_id),
  matched_at timestamptz,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS cash_receipts_engagement_idx
  ON public.cash_receipts (tenant_id, engagement_id, receipt_date);
CREATE INDEX IF NOT EXISTS cash_receipts_pay_app_idx
  ON public.cash_receipts (tenant_id, pay_app_id);
--> statement-breakpoint
ALTER TABLE public.cash_receipts
  DROP CONSTRAINT IF EXISTS cash_receipts_source_check;
ALTER TABLE public.cash_receipts
  ADD CONSTRAINT cash_receipts_source_check
  CHECK (source IN ('MANUAL','QBO_FEED')) NOT VALID;
ALTER TABLE public.cash_receipts VALIDATE CONSTRAINT cash_receipts_source_check;
--> statement-breakpoint
ALTER TABLE public.cash_receipts
  DROP CONSTRAINT IF EXISTS cash_receipts_reconciliation_status_check;
ALTER TABLE public.cash_receipts
  ADD CONSTRAINT cash_receipts_reconciliation_status_check
  CHECK (reconciliation_status IN ('UNMATCHED','FULL','PARTIAL','OVER')) NOT VALID;
ALTER TABLE public.cash_receipts VALIDATE CONSTRAINT cash_receipts_reconciliation_status_check;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS public.retainage_holdings (
  holding_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants (tenant_id),
  engagement_id uuid NOT NULL REFERENCES public.engagements (engagement_id),
  pay_app_id uuid NOT NULL REFERENCES public.pay_applications (pay_app_id) ON DELETE CASCADE,
  pay_app_line_id uuid REFERENCES public.pay_app_line_items (pay_app_line_id) ON DELETE CASCADE,
  amount_held numeric(14,2) NOT NULL DEFAULT 0,
  release_trigger text NOT NULL DEFAULT 'SUBSTANTIAL_COMPLETION',
  released_at timestamptz,
  released_pay_app_id uuid REFERENCES public.pay_applications (pay_app_id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS retainage_holdings_engagement_idx
  ON public.retainage_holdings (tenant_id, engagement_id);
CREATE INDEX IF NOT EXISTS retainage_holdings_pay_app_idx
  ON public.retainage_holdings (pay_app_id);
--> statement-breakpoint
ALTER TABLE public.retainage_holdings
  DROP CONSTRAINT IF EXISTS retainage_holdings_release_trigger_check;
ALTER TABLE public.retainage_holdings
  ADD CONSTRAINT retainage_holdings_release_trigger_check
  CHECK (release_trigger IN ('SUBSTANTIAL_COMPLETION','FINAL_PAYMENT','CONTRACT_DATE','MANUAL')) NOT VALID;
ALTER TABLE public.retainage_holdings VALIDATE CONSTRAINT retainage_holdings_release_trigger_check;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS public.handoff_validations (
  validation_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants (tenant_id),
  engagement_id uuid NOT NULL REFERENCES public.engagements (engagement_id),
  mode text NOT NULL,
  validated_by uuid REFERENCES public.users (user_id),
  validated_at timestamptz NOT NULL DEFAULT now(),
  sov_state_at_handoff text,
  sov_version_id uuid REFERENCES public.sov_versions (sov_version_id),
  missing_fields jsonb NOT NULL DEFAULT '[]'::jsonb,
  exceptions jsonb NOT NULL DEFAULT '[]'::jsonb,
  required_field_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS handoff_validations_engagement_idx
  ON public.handoff_validations (tenant_id, engagement_id, validated_at);
--> statement-breakpoint
ALTER TABLE public.handoff_validations
  DROP CONSTRAINT IF EXISTS handoff_validations_mode_check;
ALTER TABLE public.handoff_validations
  ADD CONSTRAINT handoff_validations_mode_check
  CHECK (mode IN ('ACCEPT','REJECT_NEEDS_FIX','ACCEPT_WITH_EXCEPTIONS')) NOT VALID;
ALTER TABLE public.handoff_validations VALIDATE CONSTRAINT handoff_validations_mode_check;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS public.tm_tickets (
  ticket_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants (tenant_id),
  tm_auth_id uuid NOT NULL REFERENCES public.tm_authorizations (tm_auth_id) ON DELETE CASCADE,
  engagement_id uuid NOT NULL REFERENCES public.engagements (engagement_id),
  ticket_number text NOT NULL,
  work_date date NOT NULL,
  description text,
  location jsonb NOT NULL DEFAULT '{}'::jsonb,
  labor jsonb NOT NULL DEFAULT '[]'::jsonb,
  labor_total numeric(14,2) NOT NULL DEFAULT 0,
  materials jsonb NOT NULL DEFAULT '[]'::jsonb,
  materials_subtotal numeric(14,2) NOT NULL DEFAULT 0,
  materials_markup numeric(14,2) NOT NULL DEFAULT 0,
  materials_total numeric(14,2) NOT NULL DEFAULT 0,
  equipment jsonb NOT NULL DEFAULT '[]'::jsonb,
  equipment_total numeric(14,2) NOT NULL DEFAULT 0,
  ticket_total numeric(14,2) NOT NULL DEFAULT 0,
  photos jsonb NOT NULL DEFAULT '[]'::jsonb,
  field_signoff_by uuid REFERENCES public.users (user_id),
  field_signoff_at timestamptz,
  gc_signoff_required boolean NOT NULL DEFAULT false,
  gc_signoff_name text,
  gc_signoff_at timestamptz,
  gc_signoff_evidence_ref text,
  status text NOT NULL DEFAULT 'DRAFT',
  pay_app_id uuid REFERENCES public.pay_applications (pay_app_id),
  billed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint
ALTER TABLE public.tm_tickets
  DROP CONSTRAINT IF EXISTS tm_tickets_engagement_number_uidx;
ALTER TABLE public.tm_tickets
  ADD CONSTRAINT tm_tickets_engagement_number_uidx UNIQUE (tenant_id, engagement_id, ticket_number);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS tm_tickets_tm_auth_status_idx
  ON public.tm_tickets (tenant_id, tm_auth_id, status);
CREATE INDEX IF NOT EXISTS tm_tickets_pay_app_idx
  ON public.tm_tickets (tenant_id, pay_app_id);
--> statement-breakpoint
ALTER TABLE public.tm_tickets
  DROP CONSTRAINT IF EXISTS tm_tickets_status_check;
ALTER TABLE public.tm_tickets
  ADD CONSTRAINT tm_tickets_status_check
  CHECK (status IN ('DRAFT','LOGGED','READY_FOR_GC_APPROVAL','GC_APPROVED','DISPUTED','BILLABLE','BILLED','PAID','REJECTED')) NOT VALID;
ALTER TABLE public.tm_tickets VALIDATE CONSTRAINT tm_tickets_status_check;
--> statement-breakpoint

CREATE TABLE IF NOT EXISTS public.textura_submissions (
  submission_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES public.tenants (tenant_id),
  engagement_id uuid NOT NULL REFERENCES public.engagements (engagement_id),
  pay_app_id uuid NOT NULL REFERENCES public.pay_applications (pay_app_id) ON DELETE CASCADE,
  csv_file_ref text,
  textura_submission_id text,
  submission_status text NOT NULL DEFAULT 'UPLOADED',
  submitted_at timestamptz NOT NULL DEFAULT now(),
  failure_reason text,
  created_by uuid REFERENCES public.users (user_id),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS textura_submissions_engagement_idx
  ON public.textura_submissions (tenant_id, engagement_id);
CREATE INDEX IF NOT EXISTS textura_submissions_pay_app_idx
  ON public.textura_submissions (pay_app_id);
--> statement-breakpoint
ALTER TABLE public.textura_submissions
  DROP CONSTRAINT IF EXISTS textura_submissions_status_check;
ALTER TABLE public.textura_submissions
  ADD CONSTRAINT textura_submissions_status_check
  CHECK (submission_status IN ('UPLOADED','FAILED','REJECTED','ACCEPTED','RESUBMITTED')) NOT VALID;
ALTER TABLE public.textura_submissions VALIDATE CONSTRAINT textura_submissions_status_check;
