/**
 * BAN-322 Pay Apps surface v1 — aggregator for the PayAppsTab consumer.
 *
 * Resolves an engagement kid (e.g. "PRJ-26-0001") to engagement_id, then
 * fans out parallel reads against the 6 billing tables and returns the
 * combined payload in a single round-trip. When the kid does not resolve
 * to a Postgres engagement (most pre-migration Sheets-only projects), the
 * response is shaped with `engagement: null` and empty arrays so the UI
 * can render the not-yet-migrated empty state without a second request.
 *
 *   GET /api/aia/billing/by-kid/[kid]
 */

import { NextResponse } from 'next/server';
import { and, desc, eq } from 'drizzle-orm';
import {
  db,
  engagements,
  pay_applications,
  sov_versions,
  schedule_of_values,
  retainage_holdings,
  notarization_sessions,
  billing_format_config,
} from '@/db';
import { passAiaReadGate } from '@/lib/aia/read-gate';

// SOV version states that count as "active" for line-item selection. We
// prefer LOCKED if present (the post-§4-lock snapshot), falling back to
// IN_RECONCILIATION, then the highest pre-lock state by version_number.
const ACTIVE_VERSION_PRIORITY = [
  'LOCKED',
  'IN_RECONCILIATION',
  'IN_GC_NEGOTIATION',
  'APPROVED_INTERNAL',
  'DRAFT_ESTIMATOR_STRUCTURED',
  'DRAFT_AUTOGENERATED',
  'NONE',
];

function pickActiveVersionId(
  versions: { sov_version_id: string; version_number: number; state: string }[],
): string | null {
  if (versions.length === 0) return null;
  for (const state of ACTIVE_VERSION_PRIORITY) {
    const match = versions.find((v) => v.state === state);
    if (match) return match.sov_version_id;
  }
  return versions[0].sov_version_id;
}

const EMPTY_PAYLOAD = {
  engagement: null,
  payApps: [],
  sovVersions: [],
  sovLines: [],
  retainage: [],
  latestNotarization: null,
  billingFormatConfig: null,
} as const;

export async function GET(
  req: Request,
  context: { params: Promise<{ kid: string }> },
) {
  const gate = await passAiaReadGate(req);
  if (!gate.ok) return gate.response;

  const { kid: rawKid } = await context.params;
  const kid = decodeURIComponent(rawKid).trim();
  if (!kid) {
    return NextResponse.json(
      { error: 'kid path param is required' },
      { status: 400 },
    );
  }

  const engagementRow = await db
    .select({
      engagement_id: engagements.engagement_id,
      kid: engagements.kid,
      status: engagements.status,
      engagement_type: engagements.engagement_type,
      pm_handoff_state: engagements.pm_handoff_state,
      is_test_project: engagements.is_test_project,
    })
    .from(engagements)
    .where(
      and(
        eq(engagements.tenant_id, gate.tenantId),
        eq(engagements.kid, kid),
      ),
    )
    .limit(1);

  if (engagementRow.length === 0) {
    return NextResponse.json(EMPTY_PAYLOAD);
  }

  const engagement = engagementRow[0];
  const engagementId = engagement.engagement_id;

  const [
    payApps,
    versions,
    retainage,
    notarizations,
    billingConfigs,
  ] = await Promise.all([
    db
      .select()
      .from(pay_applications)
      .where(
        and(
          eq(pay_applications.tenant_id, gate.tenantId),
          eq(pay_applications.engagement_id, engagementId),
        ),
      )
      .orderBy(desc(pay_applications.pay_app_number)),
    db
      .select()
      .from(sov_versions)
      .where(
        and(
          eq(sov_versions.tenant_id, gate.tenantId),
          eq(sov_versions.engagement_id, engagementId),
        ),
      )
      .orderBy(desc(sov_versions.version_number)),
    db
      .select()
      .from(retainage_holdings)
      .where(
        and(
          eq(retainage_holdings.tenant_id, gate.tenantId),
          eq(retainage_holdings.engagement_id, engagementId),
        ),
      ),
    db
      .select()
      .from(notarization_sessions)
      .where(
        and(
          eq(notarization_sessions.tenant_id, gate.tenantId),
          eq(notarization_sessions.engagement_id, engagementId),
        ),
      )
      .orderBy(desc(notarization_sessions.created_at))
      .limit(1),
    db
      .select()
      .from(billing_format_config)
      .where(
        and(
          eq(billing_format_config.tenant_id, gate.tenantId),
          eq(billing_format_config.engagement_id, engagementId),
        ),
      )
      .limit(1),
  ]);

  const activeVersionId = pickActiveVersionId(
    versions.map((v: { sov_version_id: string; version_number: number; state: string }) => ({
      sov_version_id: v.sov_version_id,
      version_number: v.version_number,
      state: v.state,
    })),
  );

  const sovLines = activeVersionId
    ? await db
        .select()
        .from(schedule_of_values)
        .where(
          and(
            eq(schedule_of_values.tenant_id, gate.tenantId),
            eq(schedule_of_values.engagement_id, engagementId),
            eq(schedule_of_values.sov_version_id, activeVersionId),
          ),
        )
    : [];

  return NextResponse.json({
    engagement,
    payApps,
    sovVersions: versions,
    sovLines,
    retainage,
    latestNotarization: notarizations[0] ?? null,
    billingFormatConfig: billingConfigs[0] ?? null,
    activeSovVersionId: activeVersionId,
  });
}
