/**
 * BAN-309 Pass 3a.2 PR 2 — PATCH /api/aia/schedule-of-values/{id}
 *
 * Modifies a single SOV line item. Emission of SOV_MODIFIED (Pattern A) is
 * conditional on the parent sov_versions.state:
 *   - {NONE, DRAFT_AUTOGENERATED, DRAFT_ESTIMATOR_STRUCTURED, APPROVED_INTERNAL,
 *      IN_GC_NEGOTIATION} (pre-lock) → UPDATE only, no emit
 *   - {LOCKED, IN_RECONCILIATION}    (post-lock) → UPDATE + emit
 *   - {RETIRED}                                  → reject 409
 *
 * The PATCH accepts exactly one field at a time so the emitted payload's
 * { modified_column, before_value, after_value } shape stays unambiguous.
 * Allowed fields: description, cost_code, scheduled_value, retainage_pct.
 */

import { NextResponse } from 'next/server';
import { and, eq } from 'drizzle-orm';
import {
  db,
  schedule_of_values,
  sov_versions,
  engagements,
} from '@/db';
import { passAiaApiGate } from '@/lib/aia/api-gate';
import {
  emitActivitySpineEvent,
  ActivitySpineEmitError,
} from '@/lib/activity-spine/emit';

const ROUTE_PATH = '/api/aia/schedule-of-values/[id]';

const ALLOWED_FIELDS = ['description', 'cost_code', 'scheduled_value', 'retainage_pct'] as const;
type AllowedField = typeof ALLOWED_FIELDS[number];

const POST_LOCK_STATES = new Set(['LOCKED', 'IN_RECONCILIATION']);
const FROZEN_STATES = new Set(['RETIRED']);

export async function PATCH(
  req: Request,
  context: { params: Promise<{ id: string }> },
) {
  const gate = await passAiaApiGate(req, ROUTE_PATH);
  if (!gate.ok) return gate.response;

  const { id } = await context.params;

  let body: Partial<Record<AllowedField, string | number | null>>;
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }

  const presentFields = ALLOWED_FIELDS.filter((f) => body[f] !== undefined);
  if (presentFields.length === 0) {
    return NextResponse.json(
      {
        error: `Provide exactly one of: ${ALLOWED_FIELDS.join(', ')}`,
        code: 'NO_FIELD_PROVIDED',
      },
      { status: 400 },
    );
  }
  if (presentFields.length > 1) {
    return NextResponse.json(
      {
        error: `Provide exactly one modified field per request; received ${presentFields.length}`,
        code: 'MULTIPLE_FIELDS_PROVIDED',
      },
      { status: 400 },
    );
  }
  const modifiedColumn = presentFields[0];
  const afterValueRaw = body[modifiedColumn];

  const lookup = await db
    .select({
      sov_line_id: schedule_of_values.sov_line_id,
      sov_version_id: schedule_of_values.sov_version_id,
      engagement_id: schedule_of_values.engagement_id,
      parent_state: sov_versions.state,
      is_test_project: engagements.is_test_project,
      description: schedule_of_values.description,
      cost_code: schedule_of_values.cost_code,
      scheduled_value: schedule_of_values.scheduled_value,
      retainage_pct: schedule_of_values.retainage_pct,
    })
    .from(schedule_of_values)
    .innerJoin(
      sov_versions,
      eq(schedule_of_values.sov_version_id, sov_versions.sov_version_id),
    )
    .innerJoin(
      engagements,
      eq(schedule_of_values.engagement_id, engagements.engagement_id),
    )
    .where(
      and(
        eq(schedule_of_values.sov_line_id, id),
        eq(schedule_of_values.tenant_id, gate.tenantId),
      ),
    )
    .limit(1);

  if (lookup.length === 0) {
    return NextResponse.json(
      { error: `schedule_of_values line ${id} not found` },
      { status: 404 },
    );
  }

  const line = lookup[0];

  if (FROZEN_STATES.has(line.parent_state)) {
    return NextResponse.json(
      {
        error: `parent sov_version is in state ${line.parent_state}; line modifications are not allowed`,
        code: 'PARENT_FROZEN',
      },
      { status: 409 },
    );
  }

  const beforeValue = line[modifiedColumn] as unknown;
  // Normalise numeric columns to string for jsonb consistency.
  const afterValueNormalised =
    afterValueRaw === null || afterValueRaw === undefined
      ? null
      : (modifiedColumn === 'scheduled_value' || modifiedColumn === 'retainage_pct')
      ? String(afterValueRaw)
      : String(afterValueRaw);
  const beforeValueNormalised = beforeValue === null || beforeValue === undefined ? null : String(beforeValue);

  if (beforeValueNormalised === afterValueNormalised) {
    return NextResponse.json({
      ok: true,
      sov_line_id: id,
      modified_column: modifiedColumn,
      unchanged: true,
    });
  }

  const isPostLock = POST_LOCK_STATES.has(line.parent_state);

  try {
    const result = await db.transaction(async (tx) => {
      const updateValues: Record<string, unknown> = { updated_at: new Date() };
      updateValues[modifiedColumn] = afterValueNormalised;
      await tx
        .update(schedule_of_values)
        .set(updateValues)
        .where(
          and(
            eq(schedule_of_values.sov_line_id, id),
            eq(schedule_of_values.tenant_id, gate.tenantId),
          ),
        );

      if (!isPostLock) {
        return { event_id: null as string | null };
      }

      const emit = await emitActivitySpineEvent(tx, {
        event_type: 'SOV_MODIFIED',
        scope_entity_type: 'project',
        scope_entity_id: line.engagement_id,
        entity_kind: 'schedule_of_values',
        entity_id: id,
        test_data: line.is_test_project === true,
        metadata: {
          sov_line_id: id,
          parent_sov_version_id: line.sov_version_id,
          parent_state: line.parent_state,
          modified_column: modifiedColumn,
          before_value: beforeValueNormalised,
          after_value: afterValueNormalised,
          actor: gate.actorEmail,
        },
      });

      return { event_id: emit.event_id };
    });

    return NextResponse.json({
      ok: true,
      sov_line_id: id,
      modified_column: modifiedColumn,
      before_value: beforeValueNormalised,
      after_value: afterValueNormalised,
      parent_state: line.parent_state,
      emitted: isPostLock,
      event_id: result.event_id,
    });
  } catch (err) {
    if (err instanceof ActivitySpineEmitError) {
      return NextResponse.json(
        { error: err.message, code: err.code },
        { status: 500 },
      );
    }
    return NextResponse.json(
      { error: err instanceof Error ? err.message : String(err), code: 'INTERNAL' },
      { status: 500 },
    );
  }
}
