'use client';
import { useEffect, useState } from 'react';

type CostData = {
  entries: { date: string; inputTokens: number; outputTokens: number; cacheReadTokens: number; cacheWriteTokens: number; costUsd: number; calls: number }[];
  totalCost: number;
  todayCost: number;
  totalCalls: number;
  totalInput: number;
  totalOutput: number;
  totalCacheRead: number;
  totalCacheWrite: number;
  byModel: Record<string, { input: number; output: number; cost: number; calls: number }>;
  dailyBudget?: number;
  sessionBudget?: number;
  overBudget?: boolean;
  error?: string;
};

function fmt(n: number) {
  if (n >= 1e9) return `${(n/1e9).toFixed(1)}B`;
  if (n >= 1e6) return `${(n/1e6).toFixed(1)}M`;
  if (n >= 1e3) return `${(n/1e3).toFixed(0)}K`;
  return n.toString();
}

export default function CostPanel() {
  const [data, setData] = useState<CostData | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/cost')
      .then(r => r.json())
      .then(d => { setData(d); setLoading(false); })
      .catch(() => setLoading(false));
  }, []);

  return (
    <div style={{ padding: '32px', maxWidth: 900, margin: '0 auto' }}>
      <div style={{ marginBottom: 28 }}>
        <div style={{ fontSize: 11, fontWeight: 800, letterSpacing: '0.16em', textTransform: 'uppercase', color: '#94a3b8', marginBottom: 8 }}>AI Command</div>
        <h1 style={{ fontSize: 30, fontWeight: 800, letterSpacing: '-0.04em', color: '#0f172a', margin: 0, marginBottom: 4 }}>Cost & Usage</h1>
        <p style={{ fontSize: 13, color: '#64748b', margin: 0 }}>Live from OpenClaw session logs · Anthropic API</p>
      </div>

      {loading && (
        <div style={{ background: 'white', borderRadius: 24, padding: 48, textAlign: 'center', border: '1px solid #e2e8f0' }}>
          <div style={{ width: 28, height: 28, borderRadius: '50%', border: '2px solid rgba(15,118,110,0.12)', borderTopColor: '#14b8a6', animation: 'spin 0.8s linear infinite', margin: '0 auto' }} />
          <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
        </div>
      )}

      {!loading && data && !data.error && (
        <>
          {/* Stats */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(160px,1fr))', gap: 12, marginBottom: 24,
            padding: 18, borderRadius: 24,
            background: 'linear-gradient(135deg,rgba(255,255,255,0.98) 0%,rgba(240,249,255,0.92) 50%,rgba(248,250,252,0.96) 100%)',
            border: '1px solid rgba(148,163,184,0.18)', boxShadow: '0 4px 24px rgba(15,23,42,0.06)' }}>
            {[
              { label: 'Total spend', value: `$${data.totalCost.toFixed(2)}`, helper: 'All sessions to date' },
              { label: 'Today', value: `$${data.todayCost.toFixed(2)}`, helper: 'Current day' },
              { label: 'API calls', value: data.totalCalls.toLocaleString(), helper: 'Total requests' },
              { label: 'Output tokens', value: fmt(data.totalOutput), helper: 'Generated by Kai' },
              { label: 'Cache read', value: fmt(data.totalCacheRead), helper: 'Saved 90% on these' },
            ].map(s => (
              <div key={s.label} style={{ padding: '14px 16px', borderRadius: 18, background: 'rgba(255,255,255,0.78)', border: '1px solid rgba(226,232,240,0.95)' }}>
                <div style={{ fontSize: 11, fontWeight: 800, letterSpacing: '0.14em', textTransform: 'uppercase', color: '#64748b' }}>{s.label}</div>
                <div style={{ marginTop: 6, fontSize: 28, fontWeight: 900, letterSpacing: '-0.04em', color: '#0f172a', lineHeight: 1 }}>{s.value}</div>
                <div style={{ marginTop: 6, fontSize: 11, color: '#94a3b8' }}>{s.helper}</div>
              </div>
            ))}
          </div>

          {/* Budget alert */}
          {data.overBudget && (
            <div style={{ marginBottom: 16, padding: '12px 16px', borderRadius: 16, background: 'rgba(254,242,242,0.98)', border: '1px solid rgba(239,68,68,0.3)', display: 'flex', gap: 10 }}>
              <span style={{ fontSize: 9, fontWeight: 900, letterSpacing: '0.14em', textTransform: 'uppercase', color: '#b91c1c', flexShrink: 0, marginTop: 2 }}>ALERT</span>
              <div style={{ fontSize: 13, color: '#b91c1c', fontWeight: 600 }}>
                Today&#39;s spend (${(data.todayCost||0).toFixed(2)}) exceeds the daily budget of ${(data.dailyBudget||50).toFixed(0)}. Consider throttling build work.
              </div>
            </div>
          )}
          {/* Cache savings note */}
          <div style={{ marginBottom: 20, padding: '12px 16px', borderRadius: 16, background: 'rgba(240,253,250,0.96)', border: '1px solid rgba(15,118,110,0.2)', display: 'flex', gap: 10 }}>
            <span style={{ fontSize: 9, fontWeight: 900, letterSpacing: '0.14em', textTransform: 'uppercase', color: 'rgba(15,118,110,0.7)', flexShrink: 0, marginTop: 2 }}>KAI</span>
            <div style={{ fontSize: 13, color: '#475569', lineHeight: 1.6 }}>
              Cache is saving significant cost — {fmt(data.totalCacheRead)} cache read tokens at $0.30/M vs $3.00/M regular rate. Without caching this session would cost ~${((data.totalCacheRead / 1e6) * 2.70 + data.totalCost).toFixed(0)} more.
            </div>
          </div>

          {/* By model */}
          {Object.keys(data.byModel).length > 0 && (
            <div style={{ background: 'white', borderRadius: 20, border: '1px solid #e2e8f0', boxShadow: '0 2px 12px rgba(15,23,42,0.04)', padding: '20px 24px', marginBottom: 16 }}>
              <div style={{ fontSize: 11, fontWeight: 800, letterSpacing: '0.14em', textTransform: 'uppercase', color: '#94a3b8', marginBottom: 16 }}>By Model</div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
                {Object.entries(data.byModel).sort((a,b) => b[1].cost - a[1].cost).map(([model, d]) => {
                  const pct = data.totalCost > 0 ? (d.cost / data.totalCost) * 100 : 0;
                  return (
                    <div key={model}>
                      <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 6, alignItems: 'center' }}>
                        <div>
                          <span style={{ fontSize: 14, fontWeight: 700, color: '#0f172a' }}>{model}</span>
                          <span style={{ fontSize: 12, color: '#94a3b8', marginLeft: 10 }}>{d.calls.toLocaleString()} calls</span>
                        </div>
                        <span style={{ fontSize: 14, fontWeight: 700, color: '#0f172a' }}>${d.cost.toFixed(4)}</span>
                      </div>
                      <div style={{ height: 6, background: '#f1f5f9', borderRadius: 999, overflow: 'hidden' }}>
                        <div style={{ height: '100%', width: `${pct}%`, background: '#14b8a6', borderRadius: 999 }} />
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}

          {/* Daily breakdown */}
          <div style={{ background: 'white', borderRadius: 20, border: '1px solid #e2e8f0', boxShadow: '0 2px 12px rgba(15,23,42,0.04)', overflow: 'hidden' }}>
            <div style={{ padding: '16px 24px 12px', borderBottom: '1px solid #f1f5f9' }}>
              <div style={{ fontSize: 11, fontWeight: 800, letterSpacing: '0.14em', textTransform: 'uppercase', color: '#94a3b8' }}>Daily Breakdown</div>
            </div>
            {data.entries.map(e => (
              <div key={e.date} style={{ display: 'flex', alignItems: 'center', gap: 16, padding: '14px 24px', borderBottom: '1px solid #f8fafc' }}>
                <div style={{ flex: 1 }}>
                  <div style={{ fontSize: 14, fontWeight: 700, color: '#0f172a' }}>{e.date}</div>
                  <div style={{ fontSize: 12, color: '#94a3b8', marginTop: 2 }}>
                    {fmt(e.inputTokens)}in · {fmt(e.outputTokens)}out · {fmt(e.cacheReadTokens)}cr · {e.calls} calls
                  </div>
                </div>
                <div style={{ textAlign: 'right' }}>
                  <div style={{ fontSize: 16, fontWeight: 900, letterSpacing: '-0.03em', color: e.costUsd > 100 ? '#b91c1c' : e.costUsd > 50 ? '#92400e' : '#0f172a' }}>
                    ${e.costUsd.toFixed(2)}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </>
      )}

      {!loading && data?.error && (
        <div style={{ background: '#fef2f2', border: '1px solid rgba(239,68,68,0.2)', borderRadius: 16, padding: '16px 20px' }}>
          <div style={{ fontSize: 13, fontWeight: 700, color: '#b91c1c', marginBottom: 4 }}>Error reading session logs</div>
          <div style={{ fontSize: 12, color: '#475569' }}>{data.error}</div>
        </div>
      )}
    </div>
  );
}
