import type { WarRoomIssue } from './types';

export const WAR_ROOM_FIXTURE_ISSUES: WarRoomIssue[] = [
  {
    id: 'BAN-48',
    title: 'MC: build BanyanOS AI War Room command dashboard',
    url: 'https://linear.app/banyan-os/issue/BAN-48/mc-build-banyanos-ai-war-room-command-dashboard',
    status: 'Todo',
    statusType: 'unstarted',
    priority: 'Urgent',
    priorityValue: 1,
    labels: ['Workflow: Ready for Codex', 'Risk: P1', 'Type: Build', 'Repo: MC', 'Lane: Codex', 'Area: Mission Control'],
    repo: 'MC',
    lane: 'Codex',
    area: 'Mission Control',
    risk: 'P1',
    latestCommentSummary: 'Build the first production War Room surface with a server adapter boundary, read-only Linear links, and fixture fallback.',
    updatedAt: '2026-04-27T19:32:07.243Z',
    completedAt: null,
  },
  {
    id: 'BAN-47',
    title: 'Operator: define production write-test approval gate',
    url: 'https://linear.app/banyan-os/issue/BAN-47/operator-define-production-write-test-approval-gate',
    status: 'In Review',
    statusType: 'started',
    priority: 'High',
    priorityValue: 2,
    labels: ['Workflow: Needs Sean Answer', 'State: Needs Sean Answer', 'Risk: P1', 'Type: Governance', 'Repo: Linear', 'Lane: Operator', 'Area: Verification'],
    repo: 'Linear',
    lane: 'Operator',
    area: 'Verification',
    risk: 'P1',
    latestCommentSummary: 'Needs a captain-level decision before any production write-path smoke testing is allowed.',
    updatedAt: '2026-04-27T18:19:50.193Z',
    completedAt: null,
  },
  {
    id: 'BAN-45',
    title: 'Verification: create non-production smoke fixture and test data policy',
    url: 'https://linear.app/banyan-os/issue/BAN-45/verification-create-non-production-smoke-fixture-and-test-data-policy',
    status: 'In Review',
    statusType: 'started',
    priority: 'High',
    priorityValue: 2,
    labels: ['Workflow: Needs Sean Answer', 'State: Needs Sean Answer', 'Risk: P1', 'Type: Governance', 'Repo: Both', 'Lane: Operator', 'Area: Verification'],
    repo: 'Both',
    lane: 'Operator',
    area: 'Verification',
    risk: 'P1',
    latestCommentSummary: 'Blocked on fixture ownership and rules for connected MC/FA verification without production writes.',
    updatedAt: '2026-04-27T18:19:11.869Z',
    completedAt: null,
  },
  {
    id: 'BAN-44',
    title: 'Cross-app: QA complete may call MC service update without approved auth',
    url: 'https://linear.app/banyan-os/issue/BAN-44/cross-app-qa-complete-may-call-mc-service-update-without-approved-auth',
    status: 'In Review',
    statusType: 'started',
    priority: 'Urgent',
    priorityValue: 1,
    labels: ['Workflow: Needs Review', 'State: Cross-Repo', 'Risk: P0', 'Type: Bug', 'Repo: Both', 'Lane: Codex', 'Area: Verification'],
    repo: 'Both',
    lane: 'Codex',
    area: 'Verification',
    risk: 'P0',
    latestCommentSummary: 'XO review should confirm the auth contract before implementation touches either app.',
    updatedAt: '2026-04-27T15:48:09.409Z',
    completedAt: null,
  },
  {
    id: 'BAN-41',
    title: 'Cross-app: reconcile Field_Events_V1 column map',
    url: 'https://linear.app/banyan-os/issue/BAN-41/cross-app-reconcile-field-events-v1-column-map',
    status: 'In Review',
    statusType: 'started',
    priority: 'Urgent',
    priorityValue: 1,
    labels: ['Workflow: Needs Review', 'State: Cross-Repo', 'Risk: P0', 'Type: Audit', 'Repo: Both', 'Lane: Codex', 'Area: Verification'],
    repo: 'Both',
    lane: 'Codex',
    area: 'Verification',
    risk: 'P0',
    latestCommentSummary: 'Column contract mismatch risk must be settled before issue-status, PDF, and evidence flows are trusted.',
    updatedAt: '2026-04-27T15:48:02.172Z',
    completedAt: null,
  },
  {
    id: 'BAN-29',
    title: 'MC: Compliance surface is unbuilt but renders live-looking hardcoded data',
    url: 'https://linear.app/banyan-os/issue/BAN-29/mc-compliance-surface-is-unbuilt-but-renders-live-looking-hardcoded',
    status: 'In Review',
    statusType: 'started',
    priority: 'High',
    priorityValue: 2,
    labels: ['Workflow: Needs Review', 'Risk: P2', 'Type: Bug', 'Repo: MC', 'Lane: Codex', 'Area: Mission Control'],
    repo: 'MC',
    lane: 'Codex',
    area: 'Mission Control',
    risk: 'P2',
    latestCommentSummary: 'Awaiting review on whether to hide, label, or connect the compliance surface.',
    updatedAt: '2026-04-27T15:49:29.393Z',
    completedAt: null,
  },
  {
    id: 'BAN-18',
    title: 'Estimating trunk: operator question backlog',
    url: 'https://linear.app/banyan-os/issue/BAN-18/estimating-trunk-operator-question-backlog',
    status: 'Backlog',
    statusType: 'backlog',
    priority: 'No priority',
    priorityValue: 0,
    labels: ['State: Needs Sean Answer', 'Type: Estimating', 'Lane: Operator', 'Area: Estimating Trunk'],
    repo: 'Linear',
    lane: 'Operator',
    area: 'Estimating Trunk',
    risk: 'None',
    latestCommentSummary: 'Dry-dock item for shaping the estimating trunk decision backlog.',
    updatedAt: '2026-04-27T06:45:29.351Z',
    completedAt: null,
  },
  {
    id: 'BAN-11',
    title: 'Add AGENTS.md to Mission Control repo',
    url: 'https://linear.app/banyan-os/issue/BAN-11/add-agentsmd-to-mission-control-repo',
    status: 'Done',
    statusType: 'completed',
    priority: 'No priority',
    priorityValue: 0,
    labels: ['Type: Governance', 'Repo: MC', 'Lane: Codex', 'Area: Mission Control'],
    repo: 'MC',
    lane: 'Codex',
    area: 'Mission Control',
    risk: 'None',
    latestCommentSummary: 'Repo instruction file landed and is available to future Codex sessions.',
    updatedAt: '2026-04-27T18:47:46.887Z',
    completedAt: '2026-04-27T07:06:05.679Z',
  },
];
