/**
 * BAN-309 Pass 3a.2 — Pattern B state-machine transition helpers for AIA
 * lifecycle entities (pay_applications, sov_versions, tm_authorizations,
 * lien_waivers, tm_tickets).
 *
 * Each entity owns a lifecycle column (`state` or `status`) with a
 * CHECK-constraint-bounded set of allowed values. This module centralises
 * the allowed-transition graphs so routes don't duplicate them and so the
 * validator + state-machine + emit payload stay in lockstep.
 *
 * Pattern B canon: every transition emits a *_STATE_CHANGED event with
 * from_state + to_state in metadata (per
 * lib/activity-spine/event-contract.ts:93-100).
 *
 * PR 4 (BAN-309 close-out): adds tm_ticket — the 5th and final Pattern B
 * entity. Lifecycle column is `tm_tickets.status` (schema drift; same as
 * tm_authorizations).
 */

import type { ActivitySpineEventType } from '@/lib/activity-spine/event-contract';
import type { ActivitySpineAiaEntityKind } from '@/lib/activity-spine/emit';

export type AiaPatternBEntity =
  | 'pay_application'
  | 'sov_version'
  | 'tm_authorization'
  | 'lien_waiver'
  | 'tm_ticket';

// State machines — exact strings must match the schema CHECK constraints in
// db/schema.ts. Keeping these mirrored here lets the route reject an
// illegal transition with a 400 before hitting the DB.

export const PAY_APP_STATES = [
  'PENDING_DRAFT',
  'READY_FOR_NOTARIZATION',
  'READY_FOR_SUBMISSION',
  'SUBMITTED',
  'ARCHITECT_CERTIFIED',
  'GC_APPROVED',
  'PAID_PARTIAL',
  'PAID_FULL',
  'REJECTED',
] as const;
export type PayAppState = typeof PAY_APP_STATES[number];

export const PAY_APP_ALLOWED_TRANSITIONS: Record<PayAppState, PayAppState[]> = {
  PENDING_DRAFT: ['READY_FOR_NOTARIZATION', 'READY_FOR_SUBMISSION', 'REJECTED'],
  READY_FOR_NOTARIZATION: ['READY_FOR_SUBMISSION', 'PENDING_DRAFT', 'REJECTED'],
  READY_FOR_SUBMISSION: ['SUBMITTED', 'PENDING_DRAFT', 'REJECTED'],
  SUBMITTED: ['ARCHITECT_CERTIFIED', 'REJECTED'],
  ARCHITECT_CERTIFIED: ['GC_APPROVED', 'REJECTED'],
  GC_APPROVED: ['PAID_PARTIAL', 'PAID_FULL', 'REJECTED'],
  PAID_PARTIAL: ['PAID_FULL'],
  PAID_FULL: [],
  REJECTED: ['PENDING_DRAFT'],
};

export const SOV_VERSION_STATES = [
  'NONE',
  'DRAFT_AUTOGENERATED',
  'DRAFT_ESTIMATOR_STRUCTURED',
  'APPROVED_INTERNAL',
  'IN_GC_NEGOTIATION',
  'LOCKED',
  'IN_RECONCILIATION',
  'RETIRED',
] as const;
export type SovVersionState = typeof SOV_VERSION_STATES[number];

export const SOV_VERSION_ALLOWED_TRANSITIONS: Record<SovVersionState, SovVersionState[]> = {
  NONE: ['DRAFT_AUTOGENERATED', 'DRAFT_ESTIMATOR_STRUCTURED'],
  DRAFT_AUTOGENERATED: ['DRAFT_ESTIMATOR_STRUCTURED', 'APPROVED_INTERNAL', 'RETIRED'],
  DRAFT_ESTIMATOR_STRUCTURED: ['APPROVED_INTERNAL', 'RETIRED'],
  APPROVED_INTERNAL: ['IN_GC_NEGOTIATION', 'LOCKED', 'RETIRED'],
  IN_GC_NEGOTIATION: ['APPROVED_INTERNAL', 'LOCKED', 'RETIRED'],
  LOCKED: ['IN_RECONCILIATION', 'RETIRED'],
  IN_RECONCILIATION: ['LOCKED', 'RETIRED'],
  RETIRED: [],
};

export const TM_AUTHORIZATION_STATES = ['ACTIVE', 'CLOSED', 'DISPUTED', 'CONVERTED_TO_CO'] as const;
export type TmAuthorizationState = typeof TM_AUTHORIZATION_STATES[number];

export const TM_AUTHORIZATION_ALLOWED_TRANSITIONS: Record<TmAuthorizationState, TmAuthorizationState[]> = {
  ACTIVE: ['CLOSED', 'DISPUTED', 'CONVERTED_TO_CO'],
  DISPUTED: ['ACTIVE', 'CLOSED', 'CONVERTED_TO_CO'],
  CLOSED: ['DISPUTED'],
  CONVERTED_TO_CO: [],
};

export const LIEN_WAIVER_STATES = [
  'PENDING',
  'NOTARIZED',
  'FILED',
  'DELIVERED',
  'RELEASED',
  'VOIDED',
] as const;
export type LienWaiverState = typeof LIEN_WAIVER_STATES[number];

export const LIEN_WAIVER_ALLOWED_TRANSITIONS: Record<LienWaiverState, LienWaiverState[]> = {
  PENDING: ['NOTARIZED', 'VOIDED'],
  NOTARIZED: ['FILED', 'DELIVERED', 'VOIDED'],
  FILED: ['DELIVERED', 'RELEASED', 'VOIDED'],
  DELIVERED: ['RELEASED', 'VOIDED'],
  RELEASED: [],
  VOIDED: [],
};

// PR 4 — tm_tickets. States mirror the schema CHECK on tm_tickets.status
// (AIA v1.1 §11.3). Transition graph verified against AIA v1.1 §11.5 by XO
// audit 2026-05-17; REJECTED is terminal — escalation of rejected tickets
// happens via parent TM Authorization → CO conversion
// (TM_AUTHORIZATION_CONVERTED_TO_CO emission, PR 2), not ticket reopen.
export const TM_TICKET_STATES = [
  'DRAFT',
  'LOGGED',
  'READY_FOR_GC_APPROVAL',
  'GC_APPROVED',
  'DISPUTED',
  'BILLABLE',
  'BILLED',
  'PAID',
  'REJECTED',
] as const;
export type TmTicketState = typeof TM_TICKET_STATES[number];

export const TM_TICKET_ALLOWED_TRANSITIONS: Record<TmTicketState, TmTicketState[]> = {
  DRAFT: ['LOGGED', 'REJECTED'],
  LOGGED: ['DRAFT', 'READY_FOR_GC_APPROVAL', 'REJECTED'],
  READY_FOR_GC_APPROVAL: ['GC_APPROVED', 'DISPUTED', 'REJECTED'],
  GC_APPROVED: ['BILLABLE', 'DISPUTED'],
  DISPUTED: ['READY_FOR_GC_APPROVAL', 'REJECTED'],
  BILLABLE: ['BILLED'],
  BILLED: ['PAID'],
  PAID: [],
  REJECTED: [],
};

// ── Per-entity metadata ─────────────────────────────────────────────────────

interface PatternBEntityMeta<S extends string> {
  event_type: ActivitySpineEventType;
  aia_entity_kind: ActivitySpineAiaEntityKind;
  states: readonly S[];
  transitions: Record<S, readonly S[]>;
}

export const PATTERN_B_ENTITIES: {
  pay_application: PatternBEntityMeta<PayAppState>;
  sov_version: PatternBEntityMeta<SovVersionState>;
  tm_authorization: PatternBEntityMeta<TmAuthorizationState>;
  lien_waiver: PatternBEntityMeta<LienWaiverState>;
  tm_ticket: PatternBEntityMeta<TmTicketState>;
} = {
  pay_application: {
    event_type: 'PAY_APP_STATE_CHANGED',
    aia_entity_kind: 'pay_application',
    states: PAY_APP_STATES,
    transitions: PAY_APP_ALLOWED_TRANSITIONS,
  },
  sov_version: {
    event_type: 'SOV_STATE_CHANGED',
    aia_entity_kind: 'sov_version',
    states: SOV_VERSION_STATES,
    transitions: SOV_VERSION_ALLOWED_TRANSITIONS,
  },
  tm_authorization: {
    event_type: 'TM_AUTHORIZATION_STATE_CHANGED',
    aia_entity_kind: 'tm_authorization',
    states: TM_AUTHORIZATION_STATES,
    transitions: TM_AUTHORIZATION_ALLOWED_TRANSITIONS,
  },
  lien_waiver: {
    event_type: 'LIEN_WAIVER_STATE_CHANGED',
    aia_entity_kind: 'lien_waiver',
    states: LIEN_WAIVER_STATES,
    transitions: LIEN_WAIVER_ALLOWED_TRANSITIONS,
  },
  tm_ticket: {
    event_type: 'TM_TICKET_STATE_CHANGED',
    aia_entity_kind: 'tm_ticket',
    states: TM_TICKET_STATES,
    transitions: TM_TICKET_ALLOWED_TRANSITIONS,
  },
};

// ── Validation ──────────────────────────────────────────────────────────────

export type TransitionValidationResult =
  | { ok: true }
  | { ok: false; reason: 'UNKNOWN_FROM_STATE' | 'UNKNOWN_TO_STATE' | 'TRANSITION_NOT_ALLOWED' | 'NO_OP'; message: string };

export function validatePatternBTransition(
  entity: AiaPatternBEntity,
  fromState: string,
  toState: string,
): TransitionValidationResult {
  const meta = PATTERN_B_ENTITIES[entity];
  const states = meta.states as readonly string[];
  const transitions = meta.transitions as Record<string, readonly string[]>;

  if (!states.includes(fromState)) {
    return { ok: false, reason: 'UNKNOWN_FROM_STATE', message: `Unknown ${entity} from_state: ${fromState}` };
  }
  if (!states.includes(toState)) {
    return { ok: false, reason: 'UNKNOWN_TO_STATE', message: `Unknown ${entity} to_state: ${toState}` };
  }
  if (fromState === toState) {
    return { ok: false, reason: 'NO_OP', message: `${entity} transition from ${fromState} to ${toState} is a no-op` };
  }
  if (!transitions[fromState].includes(toState)) {
    return {
      ok: false,
      reason: 'TRANSITION_NOT_ALLOWED',
      message: `${entity} transition ${fromState} → ${toState} is not allowed`,
    };
  }
  return { ok: true };
}

export function patternBEventTypeFor(entity: AiaPatternBEntity): ActivitySpineEventType {
  return PATTERN_B_ENTITIES[entity].event_type;
}

export function patternBAiaEntityKindFor(entity: AiaPatternBEntity): ActivitySpineAiaEntityKind {
  return PATTERN_B_ENTITIES[entity].aia_entity_kind;
}
