import {
  PATTERN_B_ENTITIES,
  PAY_APP_STATES,
  SOV_VERSION_STATES,
  TM_AUTHORIZATION_STATES,
  LIEN_WAIVER_STATES,
  validatePatternBTransition,
  patternBEventTypeFor,
  patternBAiaEntityKindFor,
} from '@/lib/aia/state-transitions';

describe('BAN-309 Pass 3a.2 — AIA Pattern B state transitions', () => {
  describe('state machine inventories match schema CHECK constraints', () => {
    it('pay_application 9-state machine', () => {
      expect(PAY_APP_STATES).toEqual([
        'PENDING_DRAFT',
        'READY_FOR_NOTARIZATION',
        'READY_FOR_SUBMISSION',
        'SUBMITTED',
        'ARCHITECT_CERTIFIED',
        'GC_APPROVED',
        'PAID_PARTIAL',
        'PAID_FULL',
        'REJECTED',
      ]);
    });

    it('sov_version 8-state machine matches AIA §4', () => {
      expect(SOV_VERSION_STATES).toEqual([
        'NONE',
        'DRAFT_AUTOGENERATED',
        'DRAFT_ESTIMATOR_STRUCTURED',
        'APPROVED_INTERNAL',
        'IN_GC_NEGOTIATION',
        'LOCKED',
        'IN_RECONCILIATION',
        'RETIRED',
      ]);
    });

    it('tm_authorization 4-state machine', () => {
      expect(TM_AUTHORIZATION_STATES).toEqual([
        'ACTIVE',
        'CLOSED',
        'DISPUTED',
        'CONVERTED_TO_CO',
      ]);
    });

    it('lien_waiver 6-state machine', () => {
      expect(LIEN_WAIVER_STATES).toEqual([
        'PENDING',
        'NOTARIZED',
        'FILED',
        'DELIVERED',
        'RELEASED',
        'VOIDED',
      ]);
    });
  });

  describe('event_type + aia_entity_kind mapping', () => {
    it('maps each entity to its canonical event_type', () => {
      expect(patternBEventTypeFor('pay_application')).toBe('PAY_APP_STATE_CHANGED');
      expect(patternBEventTypeFor('sov_version')).toBe('SOV_STATE_CHANGED');
      expect(patternBEventTypeFor('tm_authorization')).toBe('TM_AUTHORIZATION_STATE_CHANGED');
      expect(patternBEventTypeFor('lien_waiver')).toBe('LIEN_WAIVER_STATE_CHANGED');
    });

    it('maps each entity to its aia_entity_kind metadata key', () => {
      expect(patternBAiaEntityKindFor('pay_application')).toBe('pay_application');
      expect(patternBAiaEntityKindFor('sov_version')).toBe('sov_version');
      expect(patternBAiaEntityKindFor('tm_authorization')).toBe('tm_authorization');
      expect(patternBAiaEntityKindFor('lien_waiver')).toBe('lien_waiver');
    });

    it('exposes the same data through PATTERN_B_ENTITIES', () => {
      expect(PATTERN_B_ENTITIES.pay_application.event_type).toBe('PAY_APP_STATE_CHANGED');
      expect(PATTERN_B_ENTITIES.sov_version.aia_entity_kind).toBe('sov_version');
    });
  });

  describe('validatePatternBTransition', () => {
    it('accepts an allowed pay_app transition', () => {
      expect(validatePatternBTransition('pay_application', 'SUBMITTED', 'ARCHITECT_CERTIFIED')).toEqual({ ok: true });
    });

    it('accepts an allowed sov_version transition', () => {
      expect(validatePatternBTransition('sov_version', 'APPROVED_INTERNAL', 'LOCKED')).toEqual({ ok: true });
    });

    it('rejects an unknown from_state', () => {
      const result = validatePatternBTransition('pay_application', 'NOT_A_STATE', 'SUBMITTED');
      expect(result.ok).toBe(false);
      if (!result.ok) expect(result.reason).toBe('UNKNOWN_FROM_STATE');
    });

    it('rejects an unknown to_state', () => {
      const result = validatePatternBTransition('lien_waiver', 'PENDING', 'NOT_A_STATE');
      expect(result.ok).toBe(false);
      if (!result.ok) expect(result.reason).toBe('UNKNOWN_TO_STATE');
    });

    it('rejects a no-op transition (same state)', () => {
      const result = validatePatternBTransition('tm_authorization', 'ACTIVE', 'ACTIVE');
      expect(result.ok).toBe(false);
      if (!result.ok) expect(result.reason).toBe('NO_OP');
    });

    it('rejects a transition that exists in the graph but jumps illegally', () => {
      // pay_application: PENDING_DRAFT cannot skip directly to PAID_FULL
      const result = validatePatternBTransition('pay_application', 'PENDING_DRAFT', 'PAID_FULL');
      expect(result.ok).toBe(false);
      if (!result.ok) expect(result.reason).toBe('TRANSITION_NOT_ALLOWED');
    });

    it('rejects a transition out of a terminal state', () => {
      // pay_application.PAID_FULL is terminal
      const result = validatePatternBTransition('pay_application', 'PAID_FULL', 'GC_APPROVED');
      expect(result.ok).toBe(false);
      if (!result.ok) expect(result.reason).toBe('TRANSITION_NOT_ALLOWED');
    });

    it('rejects reopening a terminal lien_waiver', () => {
      const result = validatePatternBTransition('lien_waiver', 'RELEASED', 'PENDING');
      expect(result.ok).toBe(false);
      if (!result.ok) expect(result.reason).toBe('TRANSITION_NOT_ALLOWED');
    });

    it('allows the rejection cycle for pay_applications', () => {
      expect(validatePatternBTransition('pay_application', 'SUBMITTED', 'REJECTED')).toEqual({ ok: true });
      expect(validatePatternBTransition('pay_application', 'REJECTED', 'PENDING_DRAFT')).toEqual({ ok: true });
    });
  });
});
